# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournamentsite_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.QTourUser'),
            preserve_default=False,
        ),
    ]
