# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170430_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='multiple_sites',
            new_name='acf',
        ),
        migrations.AddField(
            model_name='tournament',
            name='announcement_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
