# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170501_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.QTourUser'),
        ),
    ]
