# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170513_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='adjustments',
            field=models.ManyToManyField(related_name='tournament_adjustments', to='core.DiscountOrPenalty'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='packet_adjustments',
            field=models.ManyToManyField(related_name='tournament_packet_adjustments', to='core.PacketDiscountOrPenalty'),
        ),
    ]
